services:

  nodered:
    image: nodered/node-red
    networks:
    - mynet
    environment:
    - SERVICE_NAME=node-red
    ports:
    - "1880:1880"
    links:
    - mosquitto
    volumes:
    - ./nodered_data:/data

  mosquitto:
    image: eclipse-mosquitto
    hostname: mosquitto
    container_name: mosquitto
    expose:
      - "1883"
      - "9001"
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - mynet

     
     
  web:
    image: nginx:stable-alpine
    container_name: granja-dashboard
    ports:
        - "81:80"
    volumes:
      - ./nginx/index.html:/usr/share/nginx/html/index.html:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - mynet

networks:
  mynet:
      driver: bridge
      driver_opts:
          com.docker.network.enable_ipv6: "true"
